import{S as l,N as u,K as d,M as p,i as a,a as f}from"./assets/vendor-1b712bb3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();new l(".reviews-wrapper",{modules:[u,d,p],direction:"horizontal",updateOnWindowResize:!0,slidesPerView:1,enabled:!0,swipeHandler:".reviews-item",speed:300,spaceBetween:20,height:302,keyboard:{enabled:!0,onlyInViewport:!1},mousewheel:{invert:!0},breakpoints:{768:{slidesPerView:2,slidesPerGroup:1,spaceBetween:16},1440:{slidesPerView:4,slidesPerGroup:1,spaceBetween:16}},navigation:{prevEl:".swiper-button-prev",nextEl:".swiper-button-next",preventClicks:!1}});let w=1;const c={container:document.querySelector(".reviews-list"),btnPrev:document.querySelector(".swiper-button-prev"),btnNext:document.querySelector(".swiper-button-next")};async function m(s){try{const r=await f.get("https://portfolio-js.b.goit.study/api/review",{params:{id:s}});if(r.status!==200)throw new Error(r.status);return r.data}catch(r){throw new Error(`Fetching reviews failed: ${r.message}`)}}async function g(){try{const r=(await m(w)).map(({_id:i,author:o,avatar_url:e,review:t})=>`
  <div class="swiper-slide">
  <li class="reviews-item " data="${i}">
  <img class="reviews-img" src="${e}" alt="${o}" loading="lazy"/>
  
  <p class="reviews-text">${t}</p>
  <h2 class="reviews-subtitle">${o}</h2>

  </li>
  </div>
  `).join("");c.container.insertAdjacentHTML("beforeend",r)}catch(s){c.container.insertAdjacentHTML("afterbegin",'<p class="reviews-error-text">Not found</p>'),v(s.message)}}g();const v=s=>{a.settings({timeout:5e3,titleColor:"#fff",position:"topRight",messageColor:"#fff",icon:"",close:!1}),a.error({message:s,class:"error-notification",timeout:5e3,titleColor:"#fff",position:"topRight",backgroundColor:"#EF4040",messageColor:"#fff",progressBarColor:"#B51B1B",close:!0})};
//# sourceMappingURL=commonHelpers.js.map
