import{S as l,N as u,K as d,M as p,i as a,a as f}from"./assets/vendor-1b712bb3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();new l(".reviews-wrapper",{modules:[u,d,p],direction:"horizontal",updateOnWindowResize:!0,slidesPerView:1,enabled:!0,swipeHandler:".reviews-item",speed:300,spaceBetween:20,height:302,keyboard:{enabled:!0,onlyInViewport:!0},mousewheel:{invert:!1},breakpoints:{768:{slidesPerView:2,slidesPerGroup:1,spaceBetween:16},1440:{slidesPerView:4,slidesPerGroup:1,spaceBetween:16}},navigation:{prevEl:".swiper-button-prev",nextEl:".swiper-button-next",preventClicks:!1}});let w=1;const c={container:document.querySelector(".reviews-list"),btnPrev:document.querySelector(".swiper-button-prev"),btnNext:document.querySelector(".swiper-button-next")};async function m(s){try{const r=await f.get("https://portfolio-js.b.goit.study/api/reviews",{params:{id:s}});if(r.status!==200)throw new Error(r.status);return r.data}catch(r){throw new Error(`Fetching reviews failed: ${r.message}`)}}async function v(){try{const r=(await m(w)).map(({_id:o,author:i,avatar_url:e,review:t})=>`
  <div class="swiper-slide">
  <li class="reviews-item " data="${o}">
  <img class="reviews-img" src="${e}" alt="${i}" loading="lazy"/>
  <h2 class="reviews-subtitle">${i}</h2>
  <p class="reviews-text">${t}</p>
  </li>
  </div>
  `).join("");c.container.insertAdjacentHTML("beforeend",r)}catch(s){c.container.insertAdjacentHTML("afterbegin",'<p class="reviews-error-text">Not found</p>'),g(s.message)}}v();const g=s=>{a.settings({timeout:5e3,titleColor:"#fff",position:"center",messageColor:"#fff",icon:""}),a.error({message:s,timeout:5e3,position:"center",backgroundColor:"#EF4040"})};
//# sourceMappingURL=commonHelpers.js.map
